services:
  aura-platform:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aura_platform
    mem_limit: 512m
    network_mode: host
    env_file:
      - .env
    restart: unless-stopped
